SELECT NAME FROM CITY WHERE COUNTRYCODE = 'USA' AND POPULATION>120000;

SELECT * FROM CITY;

SELECT * FROM CITY WHERE ID = 1661

SELECT * FROM CITY WHERE COUNTRYCODE = 'JPN' ;

SELECT NAME FROM CITY WHERE COUNTRYCODE = 'JPN' ;

SELECT DISTINCT(CITY)  FROM STATION  WHERE MOD(ID,2) = 0 ;

/*
Find the difference between the total number of CITY entries in the table and the number of distinct CITY entries in the table.
The STATION table is described as follows:
*/
SELECT (SELECT COUNT(CITY) FROM STATION) - (SELECT COUNT(DISTINCT(CITY)) FROM STATION) FROM DUAL

